# Generated by Django 5.0.4 on 2024-07-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0002_category_recurrenceperiod_budget_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
