# Generated by Django 5.0.4 on 2024-12-06 05:36

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0006_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fintrack.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fintrack.category'),
        ),
        migrations.DeleteModel(
            name='FinancialGoal',
        ),
    ]
