# Generated by Django 5.0.4 on 2024-12-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0007_bill_category_alter_budget_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
