# Generated by Django 5.0.4 on 2024-12-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0008_budget_amount_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
