# Generated by Django 5.0.4 on 2024-12-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0009_transaction_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrenceperiod',
            name='name',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Biannually', 'Biannually'), ('Annually', 'Annually')], max_length=50),
        ),
    ]
